inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  - "Gemfile"
  - "bin/**/*"
  - "db/**/*"
  - "log/**/*"
  - "tmp/**/*"
  - "vendor/**/*"
  - "config/environments/*"

Metrics:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false